config/routes.rb
Acman::Application.routes.draw do
  resources :users
  resources :groups
  resources :banlist
  resources :addrs

  resources :banlist do
    resources :addrs
  end

  match '/newuser', :to => 'users#new'
  match '/users', :to => 'users#index'

  match '/home', :to => 'pages#home'
  match '/squid', :to => 'pages#squid'
  match '/squid_update', :to => 'pages#squid_update'

  match '/newgroup', :to => 'groups#new'
  match '/groups', :to => 'groups#index'

  match '/getbanlists', :to => 'banlist#getbanlists'
  match '/listbanfiles', :to => 'banlist#listbanfiles'

  root :to => 'pages#home'

end

app/models/banlist.rb
class Banlist < ActiveRecord::Base
  has_many :addrs
  has_many :pcres
  attr_accessible :name
  validates :name, :presence => true,
            :uniqueness => true
end

app/controllers/banlist_controller.rb
class BanlistController < ApplicationController
  require 'will_paginate/array'

  def getbanlists
    banlists_path = 'd:\acman\usr\local\rejik3\banlists'
    Dir.foreach(banlists_path) do |fname|
      if fname != '.'
        if fname != '..'
          unless Banlist.find_by_name(fname)
            Banlist.create(:name => fname)
          end
          banlist = Banlist.find_by_name(fname)
          urls_path = banlists_path + '\\' + fname + '\\urls'
          if File.exist?(urls_path)
            File.new(urls_path).each_line do |line|
              unless line == '\n'
                unless banlist.addrs.find_by_name(line)
                  banlist.addrs.create(:name => line)
                end
              end
            end
          end
          pcre_path = banlists_path + '\\' + fname + '\\pcre'
          if File.exist?(pcre_path)
            File.new(pcre_path).each_line do |line|
              unless line == '\n'
                unless banlist.pcres.find_by_name(line)
                  banlist.pcres.create(:name => line)
                end
              end
            end
          end
        end
      end
    end
  end

  def listbanfiles
    @banlists = Banlist.all
  end

  def show
    @banlist = Banlist.find(params[:id])
    #@addrs = @banlist.addrs.all.paginate(:page => params[:page])
  end

  def edit
    @banlist = Banlist.find(params[:id])
  end

  def ban_addrs
    @banlist = Banlist.find(params[:id])
    @addrs = @banlist.addrs.all.paginate(:page => params[:page])
  end

  def update
    @banlist = Banlist.find(params[:id])

    respond_to do |format|
      if @banlist.update_attributes(params[:banlist])
        format.html { redirect_to @banlist, notice: 'Banlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @banlist.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/banlist_helper.rb
module BanlistHelper
end

app/views/banlist/edit.html.haml
%h1 Редактирование банлиста
= form_for(@banlist) do |f|
  - if @banlist.errors.any?
    #error_explanation
      %h2
        = pluralize(@banlist.errors.count, 'error')
        prohibited this user from being saved:
      %ul
        - @banlist.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name, 'Наименование'
    %br
    = f.text_field :name
  %br
  %br
  .actions
    = f.submit 'Создать'
%br
= link_to 'Просмотр', @banlist
|
\#{link_to 'Назад', banlist_path}

app/views/banlist/getbanlists.html.haml
%table
  %tr
    %th Имя банлиста
    %th Количество urls записей
    %th Количество pcre записей
  - Banlist.all.each do |item|
    %tr
      %td= item.name
      %td= item.addrs.all.length
      %td= item.pcres.all.length

app/views/banlist/listbanfiles.html.haml
%h1 Список банфайлов
%table
  %tr
    %th
      %strong Имя
    %th
      %strong Количество адресов
    %th
      %strong Количество regexp
    %th
    %th
    %th
  - @banlists.each do |banlist|
    %tr
      %td= banlist.name
      %td= banlist.addrs.all.length
      %td= banlist.pcres.all.length
      %td= link_to 'Адреса', [banlist, :addrs]
      %td= link_to 'Изменить', edit_banlist_path(banlist)
      %td= link_to 'Удалить', banlist, method: :delete, data: { confirm: 'Вы уверены?' }

app/views/banlist/show.html.haml
%p#notice= notice
%table
  %tr
    %td
      %strong Наименование
    %td= @banlist.name
= link_to 'Создать', new_banlist_path
|
\#{link_to 'Изменить', edit_banlist_path(@banlist)} |
\#{link_to 'Назад', banlist_path}