config/routes.rb
Acman::Application.routes.draw do
  resources :users
  resources :groups
  resources :banlist
  resources :addrs

  resources :banlist do
    resources :addrs
  end

  match '/newuser', :to => 'users#new'
  match '/users', :to => 'users#index'

  match '/home', :to => 'pages#home'
  match '/squid', :to => 'pages#squid'
  match '/squid_update', :to => 'pages#squid_update'

  match '/newgroup', :to => 'groups#new'
  match '/groups', :to => 'groups#index'

  match '/getbanlists', :to => 'banlist#getbanlists'
  match '/listbanfiles', :to => 'banlist#listbanfiles'

  root :to => 'pages#home'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true,
            :uniqueness => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @groups }
    end
  end

  def new
    @group = Group.new
    @title = 'Create new group'
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to @group
    else
      @title = 'Create group'
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @users = User.order(sort_column + ' ' + sort_direction)
    @title = @group.name
  end

  def edit
    @group = Group.find(params[:id])
    @title = @group.name
  end

  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2
        = pluralize(@group.errors.count, 'error')
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name, 'Название группы'
    %br
    = f.text_field :name
  .actions
    = f.submit 'Создать'

app/views/groups/edit.html.haml
%h1 Редактирование группы
= render 'form'
%br
= link_to 'Просмотр', @group
|
\#{link_to 'Назад', group_path}

app/views/groups/index.html.haml
%h1 Список групп пользователей
%table
  %tr
    %td
      %strong Наименование
    %th
    %th
    %th
  - @groups.each do |group|
    %tr
      %td= group.name
      %td= link_to 'Просмотр', group
      /%td= link_to 'Редактирование', edit_group_path(group)
      %td= link_to 'Удаление', group, method: :delete, data: { confirm: 'Вы уверены?' }
%br
= link_to 'Новая группа', new_group_path

app/views/groups/new.html.haml
%h1 Создание новой группы пользователей
= render 'form'
= link_to 'Назад', users_path

app/views/groups/show.html.haml
%p#notice= notice
%p
  %strong Имя группы:
  = @group.name
%strong Пользователи группы
%table
  %tr
    %th
      %strong= sortable 'surname', 'Фамилия'
    %th
      %strong= sortable 'name', 'Имя'
    %th
      %strong= sortable 's_name', 'Отчество'
    %th
      %strong= sortable 'ip', 'IP адрес'
  - @users.each do |user|
    - if user.team == @group.name
      %tr
        %td= user.surname
        %td= user.name
        %td= user.s_name
        %td= user.ip
= link_to 'Изменить', edit_group_path(@group)
|
\#{link_to 'Назад', group_path}